config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :doctors do
    resources :appointments, only: [:index, :new, :create]
  end

  resources :patients do
    resources :appointments
  end

  resources :appointments
  resources :admins


  root 'sessions#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'admins#new'
  post '/signup', to: 'admins#create'

  get '/auth/:provider/callback', to: 'sessions#omniauth'
end

app/views/admins/index.html.erb
<h1>All Admins</h1>
<ul>
<% @admins.each do |a| %>
  <li>
    <%= link_to a.username, admin_path(a) %> - currently helping <%= a.patients.size %> patients
  </li><br>
<% end %>
</ul>

app/views/admins/new.html.erb
<h1>Sign Up!</h1>

<%= form_for @admin do |a| %>
    Username: <%= a.text_field :username %><br><br>
    Password: <%= a.password_field :password %><br><br>
    Email: <%= a.email_field :email %><br><br>
    Name: <%= a.text_field :name %><br><br>
    Employee Id: <%= a.text_field :employee_id %><br><br>

    <%= a.submit %>
<% end %>

app/views/admins/show.html.erb
<h2>Welcome <%= @admin.name%>!</h2>

<h5>Email: <%= @admin.email %></h5>
<h5>Username: <%= @admin.username %></h5>
<h6>Employee ID: <%= @admin.employee_id %></h6>

<ul>
    <% @admin.patients.each do |patient| %>
        <li>
            <%= patient.last_name %>, <%= patient.first_name %><br>
            <%= patient.age %> years old
        </li>
    <% end %>
</ul>