config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :doctors do
    resources :appointments, only: [:index, :new, :create]
  end

  resources :patients do
    resources :appointments
  end

  resources :appointments
  resources :admins


  root 'sessions#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'admins#new'
  post '/signup', to: 'admins#create'

  get '/auth/:provider/callback', to: 'sessions#omniauth'
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    belongs_to :admin
    has_many :appointments
    has_many :patients, through: :appointments

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true
    validates :specialty, presence: true

    before_save do |doctor|
        doctor.first_name.titleize
        doctor.last_name.titleize
        doctor.specialty.titleize
        doctor.gender.titleize
        doctor.email.downcase!
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    before_action :require_login
    before_action :find_doctor, only: [:create, :edit, :update, :show]

    def index
        @doctors = Doctor.all
    end

    def new
        @doctor = Doctor.new
    end

    def create
        @doctor = current_admin.created_doctors.build(doctor_params)
        if @doctor.save
            redirect_to doctor_path(@doctor)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @doctor.update(doctor_params)
            redirect_to doctor_path(@doctor)
        else
            render :edit
        end
    end

    def show
    end

    private
    def find_doctor
        @doctor = Doctor.find_by(id: params[:id])
    end

    def doctor_params
        params.require(:doctor).permit(
            :first_name,
            :last_name,
            :specialty,
            :gender,
            :email,
            :admin_id
        )
    end
end

app/views/doctors/index.html.erb
<h1>All Doctors</h1>

<ul>
<% @doctors.each do |doctor| %>
    <li>
        <strong>Dr. <%= doctor.first_name + " " + doctor.last_name %></strong> -
        <%=doctor.specialty %> --> created by: <%= doctor.admin.username %> |
        <%= link_to "See all appointments", doctor_appointments_path(doctor)%> |
        <%= link_to "Add an appointment", new_doctor_appointment_path(doctor)%> |
        <%= doctor.appointments.size %>
    </li>
<% end %>
</ul>

app/views/doctors/new.html.erb
<h2>Add a New Doctor</h2>

<%= form_for @doctor do |d| %>
    First Name: <%= d.text_field :first_name %><br><br>
    Last Name: <%= d.text_field :last_name %><br><br>
    Specialty: <%= d.text_field :specialty %><br><br>
    Gender: <%= d.select :gender,options_for_select(["Male", "Female"]), include_blank: true %><br><br>
    Email: <%= d.email_field :email %><br><br>
<%= d.submit %>
<% end %>

app/views/doctors/show.html.erb
<div>
<h2>Dr. <%= @doctor.first_name + " " + @doctor.last_name %><br><br></h2>

<h5>Specialty: <%=@doctor.specialty %><br></br>
Email: <%=@doctor.email %></h5>
</div>