config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :doctors do
    resources :appointments, only: [:index, :new, :create]
  end

  resources :patients do
    resources :appointments
  end

  resources :appointments
  resources :admins


  root 'sessions#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'admins#new'
  post '/signup', to: 'admins#create'

  get '/auth/:provider/callback', to: 'sessions#omniauth'
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :doctor
    belongs_to :patient

    accepts_nested_attributes_for :doctor
    validates_associated :doctor
    scope :by_doctor, -> (doctor_id) {where("doctor_id = ?", doctor_id)}

    validates :date, presence: true
    validates :time, presence: true
    validates :patient_id, presence: true

    def username
        @username ||= self.patient.try(:admin).try(:username)
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    before_action :require_login
    before_action :find_doctor
    before_action :find_patient

    def index
        if params[:doctor_id]
            @appointments = @doctor.appointments
        elsif params[:patient_id]
            @appointments = @patient.appointments
        else
            @appointments = Appointment.all
        end
    end

    def new
        if params[:doctor_id]
            @appointment = @doctor.appointments.build
        else
            @appointment = Appointment.new
            @appointment.build_doctor
        end
    end

    def create
        if params[:doctor_id]
            @appointment = @doctor.appointments.build(appointment_params)
        else
            @appointment = Appointment.new(appointment_params)
        end
        binding.pry
         if @appointment.save
            redirect_to appointment_path(@appointment)
        else
            render :new
        end
    end

    def show
        find_appointment
    end

    private
    def find_appointment
        @appointment = Appointment.find(params[:id])
    end

    def find_doctor
        @doctor = Doctor.find_by_id(params[:doctor_id])
    end

    def find_patient
        @patient = Patient.find_by_id(params[:patient_id])
    end

    def appointment_params
        params.require(:appointment).permit(
            :date,
            :time,
            :reason,
            :weight,
            :temperature,
            :blood_pressure,
            :medications,
            :summary,
            :patient_id,
            :doctor_id,
            doctor_attributes:[
                :first_name,
                :last_name,
                :specialty,
                :gender,
                :email,
                :admin_id
            ]
        )
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper

    def doctor_form(form_builder)
        #had a few problems with this form and referenced this from StackOverflow
        if @doctor
            content_tag(:h2,"Appointments for Dr. #{@doctor.last_name}")
        else
            render partial: "doctorform", locals: { d: form_builder }
        end
    end
end

app/views/appointments/_doctorform.html.erb
Select a Doctor: <%= d.collection_select :doctor_id, Doctor.all, :id, :last_name, include_blank: true %><br><br>

Select a Patient: <%= d.collection_select :patient_id, Patient.all, :id, :last_name, include_blank: true %><br><br>

<h3>OR Create a New Doctor: </h3>

    <%= d.fields_for :doctor do |d| %>
        First Name: <%= d.text_field :first_name %><br><br>
        Last Name: <%= d.text_field :last_name %><br><br>
        Gender: <%= d.select :gender,options_for_select(["Female", "Male"]), include_blank: true %><br><br>
        Email: <%= d.email_field :email %><br><br>
        Specialty: <%= d.text_field :specialty %><br><br>
    <%= d.hidden_field :admin_id, value: current_admin.id %>
    <% end %>

app/views/appointments/index.html.erb
<ul>
<% @appointments.order(:date).each do |a| %>
  <li>
    <%= link_to "Dr." + a.doctor.last_name, doctor_path(a.doctor)%>
    appointment with : <%= link_to a.patient.first_name + " " + a.patient.last_name, patient_path(a.patient)%> on: <%= a.date %> | <%= a.time %> created by: <%= a.username %>

  </li><br>
<% end %>
</ul>

app/views/appointments/new.html.erb
<h1>Create a New Appointment</h1>

<%= form_for [@doctor, @appointment] do |d| %>
    Date: <%= d.date_field :date %><br><br>
    Time: <%= d.time_field :time %><br><br>

    Vitals:
    Weight: <%= d.text_field :weight %><br><br>
    Blood Pressure(Systolic/Diastolic): <%= d.text_field :blood_pressure %><br><br>
    Temperature: <%= d.text_field :temperature %><br><br>

    Medications:<br> <%= d.text_area :medications %><br><br>
    Visit Summary:<br> <%= d.text_area :summary %><br><br>

    Reason for Visit:<br>
    <%= d.text_area :reason %><br><br>

    <%= doctor_form(d) %>

<%= d.submit %>
<% end %>

app/views/appointments/show.html.erb
<h2>Dr. <%= @appointment.doctor.first_name + " " + @appointment.doctor.last_name %></h2><h2>with <%= @appointment.patient.first_name + " " + @appointment.patient.last_name %></h2><br>

<h5><br><%= @appointment.doctor.email %></h5>

<h3>Department of <%= @appointment.doctor.specialty %></h3>

<h4>Appointment at: <%= @appointment.date + @appointment.time %></h4>

<h4>Reason for Visit: <%= @appointment.reason %></h4>