config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :doctors do
    resources :appointments, only: [:index, :new, :create]
  end

  resources :patients do
    resources :appointments
  end

  resources :appointments
  resources :admins


  root 'sessions#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'admins#new'
  post '/signup', to: 'admins#create'

  get '/auth/:provider/callback', to: 'sessions#omniauth'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppointmentManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <nav class='navbar'>
        <%= link_to 'Logout', '/logout', method: :delete, class:'button'%>
      <%= link_to 'Patients', patients_path, class:'button'%>
      <%= link_to 'Create a Patient', new_patient_path, class:'button'%>
      <%= link_to 'Doctors', doctors_path, class:'button'%>
      <%= link_to 'Create a Doctor', new_doctor_path, class:'button'%>
      <%= link_to 'Appointments', appointments_path, class:'button'%>
      <%= link_to 'Create an Appointment', new_appointment_path, class:'button'%>
    <% else %>
        <%= link_to 'Log In', login_path %>
    <% end %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>